<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head"><?php echo $this->__('Bulk Catalogue Export') ?></h4>
    </div>
    <div class="fieldset">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label">
                    <label><b><?php echo __('Last Executed') ?></b></label>
                </td>
                <td class="value">
                    <?php if ($this->getExport()->getExecuted()): ?>
                    <?php echo Mage::getSingleton('core/date')->date('jS M Y h:i:s', $this->getExport()->getExecuted()) ?>
                    <?php else: ?>
                    <?php echo 'N/A' ?>
                    <?php endif ?>
                </td>
            </tr>
        </table>
    </div>
</div>