<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-payment-method"><?php echo Mage::helper('realtimedespatch')->__('OrderFlow') ?></h4>
    </div>
    <fieldset>
        <p>
            <a target="_blank" title="View Inventory" href="<?php echo $this->getOrderFlowInventoryUrl() ?>">
                <?php echo $this->getOrderFlowInventoryUrl() ?>
            </a>
        </p>
        <details>
            <summary>More information</summary>
            <p>
                OrderFlow users with the appropriate permissions can use the link above to view or edit the product inventory in the OrderFlow environment. Note that any changes made in OrderFlow will not be reflected in Magento.
            </p>
        </details>
    </fieldset>
</div>
