<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-payment-method"><?php echo Mage::helper('realtimedespatch')->__('OrderFlow') ?></h4>
    </div>
    <fieldset>
        <table>
            <tr>
                <td width="110"><?php echo Mage::helper('realtimedespatch')->__('Status') ?>:</td>
                <td><?php echo ($this->isExported() ? 'Exported at ' . $this->getExportedAt()  : 'Not Exported' ) ?></td>
            </tr>
		    <?php if ($this->isExported()): ?>
                <tr>
                    <td width="110"><?php echo Mage::helper('realtimedespatch')->__('Link') ?>:</td>
                    <td>
                        <a title="View Order" target="_blank" href="<?php echo $this->getOrderFlowInventoryUrl() ?>">
						    <?php echo $this->getOrderFlowInventoryUrl() ?>
                        </a>
                    </td>
                </tr>
		    <?php endif ?>
        </table>
        <br />
        <details>
            <summary>More information</summary>
            <p>
                OrderFlow users with the appropriate permissions can use the link above to view or edit the product inventory in the OrderFlow environment. Note that any changes made in OrderFlow will not be reflected in Magento.
            </p>
        </details>
    </fieldset>
</div>
