<div class="box-<?php echo $this->getSide() ?>">
    <div class="entry-edit">
        <div class="entry-edit-head">
            <h4 class="icon-head head-payment-method"><?php echo Mage::helper('sales')->__('OrderFlow') ?></h4>
        </div>
        <fieldset>
            <table>
                <tr>
                    <td width="110"><?php echo Mage::helper('realtimedespatch')->__('Status') ?>:</td>
                    <td><?php echo ($this->isExported() ? 'Exported at ' . $this->getExportedAt()  : 'Not Exported' ) ?></td>
                </tr>
		        <?php if ($this->isExported()): ?>
                    <tr>
                        <td width="110"><?php echo Mage::helper('realtimedespatch')->__('Link') ?>:</td>
                        <td>
                            <a title="View Order" target="_blank" href="<?php echo $this->getOrderFlowUrl() ?>">
						        <?php echo $this->getOrderFlowUrl() ?>
                            </a>
                        </td>
                    </tr>
		        <?php endif ?>
            </table>
            <br />
            <details>
                <summary>More information</summary>
                <p>
                    Credits or Refunds made in Magento will not update orders that have
                    already been passed to OrderFlow.
                </p>

                <p>
                    OrderFlow users with the appropriate permissions can use the link
                    above to view or edit the order in the OrderFlow environment. Note
                    that any changes made in OrderFlow will not be reflected in Magento.
                </p>

                <p>
                    As an order progresses through the OrderFlow pack and despatch process
                    the changes that can be made to it become more limited.
                </p>
            </details>
        </fieldset>
    </div>
</div>
